"""add tabla objetivo

Revision ID: 3d87bc06f5cb
Revises: 4bface74c26a
Create Date: 2025-07-20 18:49:05.419987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d87bc06f5cb'
down_revision = '4bface74c26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_metrica', sa.String(length=64), nullable=False),
    sa.Column('valor_objetivo', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nombre_metrica', name='uq_objetivo_usuario_metrica')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objetivo')
    # ### end Alembic commands ###
